In [ ]:
# Employee class is created
class Employee(object):
    # data member to count the number of Employees
    employee_Count = 0

    # constructor is created to initialize variables
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_Count += 1

    # function is created for average salary
    def average_salary(self):
        return self.salary / Employee.employee_Count

# Fulltime Employee class is created to inherit the properties of Employee class
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self, name, family, salary, department)

# Create instances of Employee and FulltimeEmployee
emp1 = Employee("Kavya", "nagulapally", 70000, "Sales")
emp2 = Employee("Shravya", "Kandukuri", 75000, "Marketing")
emp3 = Fulltime_Employee("Srija", "Madi", 65000, "IT")

print("Average Salary of emp1:", emp1.average_salary())
print("Average Salary of emp2:", emp2.average_salary())
print("Average Salary of FulltimeEmployee:", emp3.average_salary())
print("Total number of employees:", Employee.employee_Count )

Average Salary of emp1: 23333.333333333332
Average Salary of emp2: 25000.0
Average Salary of FulltimeEmployee: 21666.666666666668
Total number of employees: 3


In [ ]:
import numpy as np

# numpy array is created with random values in 4 by 5 size
random_Array = np.random.uniform(low=1, high=20, size=(4,5))

# Indices of max values
max_Indices = np.argmax(random_Array, axis=1)

# The row indices is finding
row_Indices = np.arange(random_Array.shape[0])

# exact positions of max valuesin the array
position_Indices = np.array([row_Indices, max_Indices])

# the array is converted into an array of flat indices
linear_Indices = np.ravel_multi_index(position_Indices, random_Array.shape)

# reshaping the linear array into multi dimensionanl array
random_Array.reshape((-1))[linear_Indices] = 0

print(random_Array)

[[ 6.50655229  1.93142355  0.          3.53889355 12.43980977]
 [12.41314557  0.          6.18259512  6.24655842  1.50275371]
 [ 9.7140687   0.         12.51373636 13.07438014 10.90355044]
 [ 7.6030678  10.60506959  4.36390254  0.         17.03619852]]
